source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.9'

target 'WDAsyncImageThumbnail_Tests', :exclusive => true do
  pod "WDAsyncImageThumbnail", :path => "../"
  pod 'OCMock', :inhibit_warnings => true
  pod 'Expecta'
end
