source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'WDAsyncImageThumbnail_Tests', :exclusive => true do
  pod "WDAsyncImageThumbnail", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
